#include "../../../pch.h"
#include "Literature.h"

#include <cstdlib>
#include <vector>

#include "../Backend/Time/Timer.h"


std::vector<std::string> possible_literature{
	std::string("I must not fear. Fear is the mind-killer. Fear is the little-death that brings about total obliteration. I will face my fear. I will permit it to pass over me and through me. And when it has gone past I will turn the inner eye to see its path. Where the fear has gone, there will be nothing. Only I will remain. \n-Herbert"),
	std::string("About three things I was absolutely positive.\nFirst, Edward was a vampire.\nSecond, there was a part of him - and I didn't know how potent that part might be - that thirsted for my blood.\nAnd third, I was unconditionally and irrevocably in love with him. \n-Meyer"),
	std::string("Say! I like green eggs and ham!\nI do! I like them, Sam-I-am!\nAnd I would eat them in a boat.\nAnd I would eat them with a goat...\nAnd I will eat them in the rain.\nAnd in the dark.\nAnd on a train.\nAnd in a car. And in a tree.\nThey are so good, so good, you see!\nSo I will eat them in a box.\nAnd I will eat them with a fox.\nAnd I will eat them in a house.\nAnd I will eat them with a mouse.\nAnd I will eat them here and there.\nSay! I will eat them anywhere!\nI do so like green eggs and ham!\nThank you! Thank you, Sam-I-am! \n-Seuss"),
	std::string("But, soft! what light through yonder window breaks? It is the east, and Juliet is the sun. Arise, fair sun, and kill the envious moon, Who is already sick and pale with grief, That thou her maid art far more fair than she: Be not her maid, since she is envious; Her vestal livery is but sick and green And none but fools do wear it; cast it off. It is my lady, O, it is my love! O, that she knew she were! \n-Shakespeare"),
	std::string("It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of light, it was the season of darkness, it was the spring of hope, it was the winter of despair. \n-Dickens"),
	std::string("Marley was dead, to begin with. There is no doubt whatever, about that. The register of his burial was signed by the clergyman, the clerk, the undertaker, and the chief mourner. Scrooge signed it; and Scrooge's name was good upon 'change, for anything he chose to put his hand to. Old Marley was as dead as a door-nail. \n-Dickens"),
	std::string("Many that live deserve death. And some that die deserve life. Can you give it to them? Then do not be too eager to deal out death in judgement. For even the very wise cannot see all ends. \n-Tolkien"),
	std::string("It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. \n-Austen"),
	std::string("The truth always carries the ambiguity of the words used to express it. \n-Herbert"),
	std::string("'I daresay you haven't had much practice,' said the Queen. 'When I was your age, I always did it for half-an-hour a day. Why, sometimes I've believed as many as six impossible things before breakfast.' \n-Carroll"),
	std::string("Life, with its rules, its obligations, and its freedoms, is like a sonnet: You're given the form, but you have to write the sonnet yourself. \n-L'Engle"),
	std::string("Like the moon over\nthe day my genius and brawn\nare lost on these fools\n-Haiku"),
	std::string("In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort. \n-Tolkien"),
	std::string("'Good Morning!' said Bilbo, and he meant it. The sun was shining, and the grass was very green. But Gandalf looked at him from under long bushy eyebrows that stuck out further than the brim of his shady hat. 'What do you mean?' he said. 'Do you wish me a good morning, or mean that it is a good morning whether I want it or not, or that you feel good this morning, or that it is a morning to be good on?' 'All of them at once,' said Bilbo. \n-Tolkien"),
	std::string("'Good morning!' he said at last. 'We don't want any adventures here, thank you! You might try over The Hill or across The Water.' By this he meant that the conversation was at an end. 'What a lot of things you do use Good morning for!' said Gandalf. 'Now you mean that you want to get rid of me, and that it won't be good till I move off.” \n-Tolkien"),
	std::string("'There is nothing like looking, if you want to find something. You certainly usually find something, if you look, but it is not always quite the something you were after.' \n-Tolkien"),
	std::string("Drummer, beat, and piper, blow.\nHarper, strike, and soldier, go.\nFree the flame and sear the grasses,\nTil the dawning Red Star passes. \n-McCaffrey"),
	std::string("The tears I feel today\nI'll wait to shed tomorrow.\nThough I'll not sleep this night\nNor find surcease from sorrow.\nMy eyes must keep their sight:\nI dare not be tear-blinded.\nI must be free to talk\nNot choked with grief, clear-minded.\nMy mouth cannot betray\nThe anguish that I know.\nYes, I'll keep my tears til later:\nBut my grief will never go. \n-McCaffrey"),
	std::string("Who wills,\nCan.\nWho tries,\nDoes.\nWho loves,\nLives. \n-McCaffrey"),
	std::string("The little queen all golden\nFlew hissing at the sea.\nTo stop each wave\nHer clutch to save\nShe ventured bravely.\nAs she attacked the sea in rage\nA holderman came nigh\nAlong the sand\nFishnet in hand\nAnd saw the queen midsky.\nHe stared at her in wonder\nFor often he'd been told\nThat such as she\nCould never be\nWho hovered there, bright gold.\nHe saw her plight and quickly\nHe looked up the cliff he faced\nAnd saw a cave\nAbove the wave\nIn which her eggs he placed.\nThe little queen all golden\nUpon his shoulder stood\nHer eyes all blue\nGlowed of her true\nUndying gratitude. \n-McCaffrey"),
	std::string("Harper, treat your words with care\nFor they may cause joy or despair\nSing your songs of health and love\nOf dragons flaming from above. \n-McCaffrey"),
	std::string("There was only one catch and that was Catch-22, which specified that a concern for one's safety in the face of dangers that were real and immediate was the process of a rational mind. Orr was crazy and could be grounded. All he had to do was ask, and as soon as he did, he would no longer be crazy and would have to fly more missions. Orr would be crazy to fly more missions and sane if he didn't, but if he was sane he had to fly them. If he flew them he was crazy and didn't have to, but if he didn't want to he was sane and had to. \n-Heller"),
	std::string("'They're trying to kill me,' Yossarian told him calmly. 'No one's trying to kill you,' Clevinger cried. 'Then why are they shooting at me?' Yossarian asked. 'They're shooting at everyone,' Clevinger answered. 'They're trying to kill everyone.' And what difference does that make? \n-Heller"),
	std::string("You have brains in your head. You have feet in your shoes.\nYou can steer yourself any direction you choose.\nYou're on your own. And you know what you know.\nAnd YOU are the one who'll decide where to go... \n-Suess"),
	std::string("When you have eliminated all which is impossible, then whatever remains, however improbable, must be the truth. \n-Doyle"),
	std::string("'My mind,' he said, 'rebels at stagnation. Give me problems, give me work, give me the most abstruse cryptogram or the most intricate analysis, and I am in my own proper atmosphere. I can dispense then with artificial stimulants. But I abhor the dull routine of existence. I crave for mental exaltation. That is why I have chosen my own particular profession, or rather created it, for I am the only one in the world.' \n-Doyle"),
	std::string("Life is infinitely stranger than anything which the mind of man could invent. We would not dare to conceive the things which are really mere commonplaces of existence. If we could fly out of that window hand in hand, hover over this great city, gently remove the roofs, and and peep in at the queer things which are going on, the strange coincidences, the plannings, the cross-purposes, the wonderful chains of events, working through generations, and leading to the most outre results, it would make all fiction with its conventionalities and foreseen conclusions most stale and unprofitable. \n-Doyle"),
	std::string("The story so far:\nIn the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move. \n-Adams"),
	std::string("For instance, on the planet Earth, man had always assumed that he was more intelligent than dolphins because he had achieved so much-the wheel, New York, wars and so on-whilst all the dolphins had ever done was muck about in the water having a good time. But conversely, the dolphins had always believed that they were far more intelligent than man—for precisely the same reasons. \n-Adams"),
	std::string("It is known that there are an infinite number of worlds, simply because there is an infinite amount of space for them to be in. However, not every one of them is inhabited. Therefore, there must be a finite number of inhabited worlds. Any finite number divided by infinity is as near to nothing as makes no odds, so the average population of all the planets in the Universe can be said to be zero. From this it follows that the population of the whole Universe is also zero, and that any people you may meet from time to time are merely the products of a deranged imagination. \n-Adams"),
	std::string("Far over the misty mountains cold\nTo dungeons deep and caverns old\nWe must away,\nere break of day,\nTo seek the pale enchanted gold.\nThe dwarves of yore made mighty spells,\nWhile hammers fell like ringing bells\nIn places deep,\nwhere dark things sleep,\nIn hollow halls beneath the fells.\nFor ancient king and elvish lord\nThere many a gleaming golden hoard\nThey shaped and wrought,\nand light they caught\nTo hide in gems on hilt of sword.\nOn silver necklaces they strung\nThe flowering stars, on crowns they hung\nThe dragon-fire,\nin twisted wire\nThey meshed the light of moon and sun. \n-Tolkien"),
	std::string("Far over the misty mountains cold\nTo dungeons deep and caverns old\nWe must away,\nere break of day,\nTo claim our long-forgotten gold.\nGoblets they carved there for themselves And harps of gold, where no man delves\nThere lay they long,\nand many a song\nWas sung unheard by men or elves.\nThe pines were roaring on the height,\nThe winds were moaning in the night.\nThe fire was red,\nit flaming spread.\nThe trees like torches blazed with light. \n-Tolkien"),
	std::string("The bells were ringing in the dale\nAnd men looked up with faces pale.\nThen dragon's ire\nmore fierce than fire\nLaid low their towers and houses frail.\nThe mountain smoked beneath the moon.\nThe dwarves, they heard the tramp of doom.\nThey fled their hall,\nto dying fall\nBeneath his feet, beneath the moon.\nFar over the misty mountains grim\nTo dungeons deep and caverns dim\nWe must away,\nere break of day,\nTo win our harps and gold from him! \n-Tolkien"),
	std::string("Roads go ever ever on,\nOver rock and under tree,\nBy caves where never sun has shone,\nBy streams that never find the sea.\nOver snow by winter sown,\nAnd through the merry flowers of June,\nOver grass and over stone,\nAnd under mountains of the moon.\nRoads go ever ever on\nUnder cloud and under star,\nYet feet that wandering have gone\nTurn at last to home afar.\nEyes that fire and sword have seen\nAnd horror in the halls of stone\nLook at last on meadows green\nAnd trees and hills they long have known. \n-Tolkien"),
	std::string("Three Rings for the Elven-kings under the sky,\nSeven for the Dwarf-lords in their halls of stone,\nNine for Mortal Men doomed to die,\nOne for the Dark Lord on his dark throne\nIn the Land of Mordor where the Shadows lie.\nOne Ring to rule them all, One Ring to find them,\nOne Ring to bring them all, and in the darkness bind them,\nIn the Land of Mordor where the Shadows lie. \n-Tolkien"),
	std::string("All that is gold does not glitter,\nNot all those who wander are lost.\nThe old that is strong does not wither,\nDeep roots are not reached by the frost.\nFrom the ashes a fire shall be woken,\nA light from the shadows shall spring.\nRenewed shall be blade that was broken,\nThe crownless again shall be king. \n-Tolkien"),
	std::string("Gone away, gone ahead,\nEchoes roll unanswered.\nEmpty, open, dusty, dead,\nWhy have all the Weyrfolk fled?\nWhere have dragons gone together?\nLeaving Weyrs to wind and weather?\nSetting herdbeasts free of tether?\nGone, our safeguards, gone, but whither?\nHave they flown to some new Weyr\nWhen cruel Threads some others fear?\nAre they worlds away from here?\nWhy, oh, why, the empty Weyr? \n-McCaffrey"),
	std::string("Love, which quickly arrests the gentle heart,\nSeized him with my beautiful form\nThat was taken from me, in a manner which still grieves me.\nLove, which pardons no beloved from loving,\ntook me so strongly with delight in him\nThat, as you see, it still abandons me not... \n-Alighieri"),
	std::string("I cannot express it, but surely you and everybody have a notion that there is or should be an existence of yours beyond you. What were the use of my creation, if I were entirely contained here? My great miseries in this world have been Heathcliff's miseries, and I watched and felt each from the beginning: my great thought in living is himself. If all else perished, and he remained, I should still continue to be, and if all else remained, and he were annihilated, the universe would turn to a mighty stranger: I should not seem a part of it. \n-Bronte"),
	std::string("I have dreamt in my life, dreams that have stayed with me ever after, and changed my ideas. They have gone through and through me, like wine through water, and altered the color of my mind. And this is one: I'm going to tell it - but take care not to smile at any part of it. \n-Bronte"),
	std::string("This story shall the good man teach his son,\nAnd Crispin Crispian shall ne'er go by,\nFrom this day to the ending of the world,\nBut we in it shall be remembered.\nWe few, we happy few, we band of brothers.\nFor he to-day that sheds his blood with me\nShall be my brother. \n-Shakespeare"),
	std::string("However mean your life is, meet it and live it. Do not shun it and call it hard names. It is not so bad as you are. It looks poorest when you are richest. The fault-finder will find faults even in paradise. Love your life, poor as it is. You may perhaps have some pleasant, thrilling, glorious hours, even in a poorhouse. The setting sun is reflected from the windows of the almshouse as brightly as from the rich man's abode; the snow melts before its door as early in the spring. I do not see but a quiet mind may live as contentedly there, and have as cheering thoughts, as in a palace. \n-Thoreau"),
	std::string("We must learn to reawaken and keep ourselves awake, not by mechanical aids, but by an infinite expectation of the dawn, which does not forsake us even in our soundest sleep. I know of no more encouraging fact than the unquestionable ability of man to elevate his life by a conscious endeavour. It is something to be able to paint a particular picture, or to carve a statue, and so to make a few objects beautiful, but it is far more glorious to carve and paint the very atmosphere and medium through which we look, which morally we can do. To affect the quality of the day, that is the highest of arts. \n-Thoreau"),
	std::string("If one advances confidently in the direction of his dreams, and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours. He will put some things behind, will pass an invisible boundary. New, universal, and more liberal laws will begin to establish themselves around and within him, or the old laws be expanded, and interpreted in his favor in a more liberal sense, and he will live with the license of a higher order of beings. \n-Thoreau"),
	std::string("I'm nobody!\nWho are you?\nAre you nobody, too?\nThen there's a pair of us, don't tell!\nThey'd banish us, you know.\nHow dreary to be somebody!\nHow public, like a frog\nTo tell your name the livelong day\nTo an admiring bog! -Dickinson"),
	std::string("How happy is the little stone\nThat rambles in the road alone,\nAnd doesn't care about careers,\nAnd exigencies never fears.\nWhose coat of elemental brown\nA passing universe put on.\nAnd independent as the sun,\nAssociates or glows alone,\nFulfilling absolute decree\nIn casual simplicity. \n-Dickinson"),
	std::string("Because I could not stop for death\nHe kindly stopped for me.\nThe carriage held but just ourselves\nAnd immortality \n-Dickinson"),
	std::string("For, like almost everyone else in our country, I started out with my share of optimism. I believed in hard work and progress and action, but now, after first being 'for' society and then 'against' it, I assign myself no rank or any limit, and such an attitude is very much against the trend of the times. But my world has become one of infinite possibilities. What a phrase - still it's a good phrase and a good view of life, and a man shouldn't accept any other; that much I've learned underground. Until some gang succeeds in putting the world in a strait jacket, its definition is possibility. \n-Ellison"),
	std::string("Turmoil has engulfed the Galactic Republic. The taxation of trade routes to outlying star systems is in dispute.\n\nHoping to resolve the matter with a blockade of deadly battleships, the greedy Trade Federation has stopped all shipping to the small planet of Naboo.\n\nWhile the Congress of the Republic endlessly debates this alarming chain of events, the Supreme Chancellor has secretly dispatched two Jedi Knights, the guardians of peace and justice in the galaxy, to settle the conflict...."),
	std::string("There is unrest in the Galactic Senate. Several thousand solar systems have declared their intentions to leave the Republic.\n\nThis separatist movement, under the leadership of the mysterious Count Dooku, has made it difficult for the limited number of Jedi Knights to maintain peace and order in the galaxy.\n\nSenator Amidala, the former Queen of Naboo, is returning to the Galactic Senate to vote on the critical issue of creating an ARMY OF THE REPUBLIC to assist the overwhelmed Jedi...."),
	std::string("War! The Republic is crumbling under attacks by the ruthless Sith Lord, Count Dooku.\nThere are heroes on both sides.\nEvil is everywhere.\n\nIn a stunning move, the fiendish droid leader, General Grievous, has swept into the Republic capital and kidnapped Chancellor Palpatine, leader of the Galactic Senate.\n\nAs the Separatist Droid Army attempts to flee the besieged capital with their valuable hostage, two Jedi Knights lead a desperate mission to rescue the captive Chancellor...."),
	std::string("It is a period of civil war. Rebel spaceships, striking from a hidden base, have won their first victory against the evil Galactic Empire.\n\nDuring the battle, Rebel spies managed to steal secret plans to the Empire's ultimate weapon, the DEATH STAR, an armored space station with enough power to destroy an entire planet.\n\nPursued by the Empire's sinister agents, Princess Leia races home aboard her starship, custodian of the stolen plans that can save her people and restore freedom to the galaxy...."),
	std::string("It is a dark time for the Rebellion. Although the Death Star has been destroyed, Imperial troops have driven the Rebel forces from their hidden base and pursued them across the galaxy.\n\nEvading the dreaded Imperial Starfleet, a group of freedom fighters led by Luke Skywalker has established a new secret base on the remote ice world of Hoth.\n\nThe evil lord Darth Vader, obsessed with finding young Skywalker, has dispatched thousands of remote probes into the far reaches of space...."),
	std::string("Luke Skywalker has returned to his home planet of Tatooine in an attempt to rescue his friend Han Solo from the clutches of the vile gangster Jabba the Hutt.\n\nLittle does Luke know that the GALACTIC EMPIRE has secretly begun construction on a new armored space station even more powerful than the first dreaded Death Star.\n\nWhen completed, this ultimate weapon will spell certain doom for the small band of rebels struggling to restore freedom to the galaxy..."),
	std::string("Luke Skywalker has vanished. In his absence, the sinister FIRST ORDER has risen from the ashes of the Empire and will not rest until Skywalker, the last Jedi, has been destroyed.\n\nWith the support of the REPUBLIC, General Leia Organa leads a brave RESISTANCE. She is desperate to find her brother Luke and gain his help in restoring peace and justice to the galaxy.\n\nLeia has sent her most daring pilot on a secret mission to Jakku, where an old ally has discovered a clue to Luke's whereabouts...."),
	std::string("The FIRST ORDER reigns. Having decimated the peaceful Republic, Supreme Leader Snoke now deploys his merciless legions to seize military control of the galaxy.\n\nOnly General Leia Organa's band of RESISTANCE fighters stand against the rising tyranny, certain that Jedi Master Luke Skywalker will return and restore a spark of hope to the fight.\n\nBut the Resistance has been exposed. As the First Order speeds toward the rebel base, the brave heroes mount a desperate escape...."),
	std::string("The dead speak! The galaxy has heard a mysterious broadcast, a threat of REVENGE in the sinister voice of the late EMPEROR PALPATINE.\n\nGENERAL LEIA ORGANA dispatches secret agents to gather intelligence, while REY, the last hope of the Jedi, trains for battle against the diabolical FIRST ORDER.\n\nMeanwhile, Supreme Leader KYLO REN rages in search of the phantom Emperor, determined to destroy any threat to his power...."),
	std::string("Shadow: That blue hedgehog again of all places... \nSonic: I've found you, faker! \nShadow: Faker? I think you're the fake hedgehog around here. You're comparing yourself to me? Ha! You're not even good enough to be my fake! \nSonic: I'll make you eat those words!"),
	std::string("“Prophet!” said I, “thing of evil!—prophet still, if bird or devil! \nBy that Heaven that bends above us—by that God we both adore— \nTell this soul with sorrow laden if, within the distant Aidenn, \nIt shall clasp a sainted maiden whom the angels name Lenore— \nClasp a rare and radiant maiden whom the angels name Lenore.” \nQuoth the Raven “Nevermore.” \n\n“Be that word our sign of parting, bird or fiend!” I shrieked, upstarting—\n“Get thee back into the tempest and the Night’s Plutonian shore!\nLeave no black plume as a token of that lie thy soul hath spoken!\nLeave my loneliness unbroken!—quit the bust above my door!\nTake thy beak from out my heart, and take thy form from off my door!”\nQuoth the Raven “Nevermore.”\n-Poe"),
	std::string("The moon is a location and celestial body that appears in the Sonic the Hedgehog series. It is the only satellite of Earth. It rotates around the Earth along with the sun, making it the only glowing celestial body in the sky during the night time on Earth along with the stars. It did not have much of a role in Sonic games at first, only appearing in the background of several Zones until it became a notorious, minor plot element from the events of Sonic Adventure 2 and even becoming a setting of the titular extra Zone in Sonic Advance.\n\nDuring Sonic Adventure 2, Dr. Eggman is seen blowing up half of the moon using the Eclipse Cannon, but it is shown to be full again by Sonic Advance and Sonic Heroes. It has led to common confusion, leaving questions and theories about whatever happened to the moon in between later games. Later at Sonic Boom 2013, Takashi Iizuka explained that only what is now the dark side of the moon was destroyed.Meaning, the games following are showing the other, unaffected side, is facing the planet as a full moon."),
	std::string("When performing Blow Kiss, Amy walks up in front of her team and blows a kiss to anyone on her side of the battlefield in order to encourage them to do their best. When doing so, a line of red lips moves from Amy to her target, who will then show red hearts when the line touches him/her.\n\nIn gameplay, when performing Blow Kiss, the player is able to give any of his / hers characters currently in battle the Empowered status effect for a few rounds.The higher the level of Blow Kiss is, the greater effect will the Empowered status effect have on the target."),
	std::string("Sonic Adventure 2 is a platforming video game in the Sonic the Hedgehog series published by Sega for the Dreamcast. It is the sequel to Sonic Adventure, released in June 2001 to celebrate the 10th anniversary of the franchise. This was the final title in the series to be released on a Sega console before the company transitioned to a third party developer. Sonic Adventure 2 is notable for marking the debut of Shadow the Hedgehog, a black hedgehog that resembles Sonic the Hedgehog with similar powers, and Rouge the Bat, an enigmatic treasure hunter.\n\nSonic Adventure 2 was built around the dichotomy of 'good and evil', and thus features Hero and Dark storylines. In the Hero storyline, Sonic is framed as an escapee and teams up with Tails, Knuckles, and Amy to stop Dr.Eggman, who plans to subdue the world with the Eclipse Cannon, a superweapon stored at the Space Colony ARK. Conversely, the Dark storyline features Eggman as he attempts to conquer the world using the same weapon with Shadow and Rouge's help. The game carries on its predecessor's gameplay but introduces three distinct styles for its six playable characters: Sonic and Shadow focus on high - speed platforming, Tails and Eggman on shoot 'em up sequences, and Knuckles and Rouge on treasure hunting. The Chao system from the first game is expanded, allowing players to raise Hero and Dark Chao as a reflection of the game's central theme."),
	std::string("The Earth, also known as Sonic's world, is the overall main setting of the Sonic the Hedgehog series. Notable for its many oddities and hidden wonders, it is a lush and beautiful planet in Sonic's universe, inhabited by various creatures, most notably humans and anthropomorphic animals.\n\nThroughout its history spanning over a billion years, the Earth has seen the rise and fall of ancient civilizations, major wars, plagues and tragedies, and visits from beings from other planets. Unfortunately, various members of its inhabitants have developed weapons of mass destruction, and several power-hungry tyrants have caused crises and even catastrophes. Due to this, the Earth is far from peaceful, and though some have implored its inhabitants to live together harmoniously without violence, no attempts at permanent peace in the world have been successful. Nonetheless, the majority of the people on Earth are well meaning at heart and only wish to live their lives and make their dreams come true."),
	std::string("Japan is a location mentioned in Shadow the Hedgehog. It is a country affiliated with the United Federation.\n\nAfter the war against the Black Arms was over, the President was scheduled to meet with the Chief Cabinet Secretary of Japan for 'tea time'.\n\nIn the Sonic the Hedgehog film series produced by Paramount Pictures, Japan is a country on Earth.\nJapan is based off of the real world country of the same name.\nSonic(alongside Eggman), the series,and the brand made its start in Japan before making the transition worldwide."),
	std::string("The servers are the 7 Chaos. Chaos is power... Power enriched by the heart. The controller is the one that unifies the Chaos."),
	std::string("I don't quite know what happened or what went wrong. Was it a mistake to create the ultimate life form? I thought it would be something that would benefit mankind. But then the military guards landed on the colony that day. They were sent to destroy the research project that I had been working on. My colleagues at the research facility, my granddaughter, Maria. I hope you are all safe.\n\nThe colony was completely shut down, probably to keep the prototype from falling into the wrong hands. The ARK was shut down under the premise that there had been an accident.\n\nI found Maria's name among those who died when the ARK was shut down. She meant everything to me and I couldn't bear the thought that she died because of my research. I lost everything. I had nothing more to live for... I went insane. All I could think about was to avenge her... somehow, someway. I got scared as I was no longer able to control my thoughts. All I could think about was that I wanted it all to end.\n\nBased on my original projections, I was able to complete my project, Shadow. I designed its mind to be perfect, pure. I will leave everything to him. If you wish, release and awaken it, to the world. If you wish to fill the world with destruction..."),
	std::string("Big the Cat is a character that appears in the Sonic the Hedgehog series. He is a large, purple, anthropomorphic cat who lives deep within Mystic Ruins. Though imposing of stature, Big is gentle, calm and easy-going, though somewhat dim-witted person with a heart of gold. He also possesses incredible strength and toughness that makes him one of Sonic's strongest allies. He is also an expert fisherman.\n\nBig spends most of his time fishing in tranquility with his best friend, Froggy. Not one for going on grand adventures, Big prefers his peaceful and quiet lifestyle in the jungle. However, should his friends be in danger or in need of his aid, Big will not hesitate to leave his home to help them out and protect them in any way he can such as when he joined up with Team Rose."),
	std::string("Spagonia is a country on earth found on a peninsula in the south of Europe, apparently nearby other countries like Greece. Its national symbol is its clocktower, and its flag has a crest representing the royal family that once ruled the place. Its urban area is nearby some mountains and a lake, and its limits are marked by a giant wall.\n\nSpagonian culture is very rich. Famed for its craftsmanship, one can find pieces with a raised, solid stone relief, which itself takes tremendous skill to carve out. The cuisine makes use of tomatoes. A local dish includes the 'Brainiac Dog', a hot dog said to increase one's intellectual capacity when eaten."),
	std::string("Tarnished, a word.\n\nWhat if you booted up Resident Evil 4 Remake and Ashley was just a tiny mouse. What would you do?\n\nJust, imagine this: There she is standing there, cute as a button, and with a high-pitched voice she cries out: \"Leon! Help!I can't reach the Gorgonzola! Leon!\".\n\nAnd then after you have helped her up in some sort of quick-time mousecapade, she turns to you, looks you dead in the eyes and says: \"Cheese Whiz, mister! Thanks for the help!\". What would you do?\n\n\nAnyways, find the Albinauric woman."),
	std::string("He-he-here we go!\n\nSo they're finally here, performing for you. If you know the words, you can join in too. Put your hands together, if you want to clap. As we take you through this monkey rap! Huh!\n\nDK! Donkey Kong!\n\nHe's the leader of the bunch, you know him well. He's finally back to kick some tail. His coconut gun can fire in spurts. If he shoots ya, it's gonna hurt! He's bigger, faster, and stronger too! He's the first member of the DK crew! Huh!\n\nDK! Donkey Kong! DK! Donkey Kong is here!\n\nThis Kong's got style, so listen up dudes. She can shrink in size, to suit her mood. She's quick and nimble when she needs to be. She can float through the air and climb up trees! If you choose her, you'll not choose wrong; With a skip and a hop, she's one cool Kong! Huh!\n\nDK! Donkey Kong!\n\nHe has no style, he has no grace. This Kong has a funny face. He can handstand when he needs to, And stretch his arms out, just for you. Inflate himself just like a balloon. This crazy Kong just digs this tune! Huh!\n\nDK! Donkey Kong! DK! Donkey Kong is here!\n\nHe's back again and about time too, And this time he's in the mood! He can fly real high with his jetpack on; With his pistols out, he's one tough Kong! He'll make you smile when he plays his tune, But Kremlings beware 'cause he's after you! Huh!\n\nDK! Donkey Kong! Huh!\n\nFinally, he's here for you: It's the last member of the DK crew! This Kong's so strong, it isn't funny. Can make a Kremling cry out for mummy. Can pick up a boulder with relative ease. Makes crushing rocks seem such a breeze. He may move slow, he can't jump high, But this Kong's one hell of a guy!\n\nC'mon Cranky, take it to the fridge!\n\nWalnuts, peanuts, pineapple smells,\nGrapes, melons, oranges and coconut shells. Aww yeah!\nWalnuts, peanuts, pineapple smells,\nGrapes, melons, oranges and coconut shells. Aww yeah!"),
	std::string("I'm fully aware of what I'm doing. Can't you see? Man committed a sin... disturbing the life cycle of nature... The original sin that man is responsible to... To protect the life cycle. I have made a creature to rule over mankind... This is the final battle. Show yourself! Our new ruler, the Emperor!"),
	std::string("Light thinks it travels faster than anything but it is wrong. No matter how fast light travels, it finds the darkness has always got there first, and is waiting for it. \n-Pratchet"),
	std::string("It would be difficult for me to tell you what the moral of this story is. For some stories, it's easy. The moral of 'The Three Bears,' for instance, is 'Never break into someone else's house.' The moral of 'Snow White' is 'Never eat apples.' The moral of World War I is 'Never assassinate Archduke Ferdinand. \nSnicket"),
	std::string("Tell me. For whom do you fight?\n\nHmph! How very glib. And do you believe in Eorzea? Eorzea's unity is forged of falsehoods. Its city-states are built on deceit. And its faith is an instrument of deception.\n\nIt is naught but a cobweb of lies. To believe in Eorzea is to believe in nothing.In Eorzea, the beast tribes often summon gods to fight in their stead--though your comrades only rarely respond in kind. Which is strange, is it not?\n\nAre the 'Twelve' otherwise engaged? I was given to understand they were your protectors. If you truly believe them your guardians, why do you not repeat the trick that served you so well at Carteneau, and call them down? They will answer--so long as you lavish them with crystals and gorge them on aether. Your gods are no different than those of the beasts--eikons every one. Accept but this, and you will see how Eorzea's faith is bleeding the land dry."),
	//std::string(""),
};


void Literature::OnGameStart(MinigameManagerData data)
{
	this->currentState = MinigameState::MGS_InProgress;

	this->CreateHierarchy(data);
}

void Literature::OnFrame(MinigameManagerData data)
{
	if (data.managerState == MinigameState::MGS_InProgress)
	{
		this->OnFrameSimulate(data);
	}
}

void Literature::OnFrameSimulate(MinigameManagerData data)
{
	this->textNode->Translate({ 0, -this->textScrollSpeedY, 0 });

	if (this->textNode->GetPositionGlobal().y < -this->textBox->GetHeight())
	{
		currentState = MGS_Draw;
	}
}

void Literature::CreateHierarchy(MinigameManagerData data)
{
	std::string chosen_text = possible_literature[RandomInt(0, possible_literature.size())];

	// Player
	this->textNode = data.hierarchy->CreateNode("Text");
	textNode->SetPositionGlobal({ 320.0f, 480.0f, 0.0f });
	textNode->displaySize = { 610.0f, 10.0f, 0.0f };
	this->textBox = new TextBox(chosen_text.c_str(), 48.0f, TextAlignment::Center, data.text);
	textNode->renderComponents.push_back(this->textBox);
}
